# -*- coding: utf-8 -*-
"""FUTURE_ML_01_Sales_Forecasting..py script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bf4Sb1urKS9z9zyVHrQly-sYaopdVKTg
"""

import pandas as pd
import matplotlib.pyplot as plt
from prophet import Prophet

import zipfile
import os

zip_path = "archive.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

os.listdir()

import pandas as pd
df = pd.read_csv("Sample - Superstore.csv", encoding="ISO-8859-1")
df.head()

df.columns

df['Order Date'] = pd.to_datetime(df['Order Date'])
sales_df = df[['Order Date', 'Sales']]
sales_df.columns = ['ds', 'y']
sales_df.head()

daily_sales = sales_df.groupby('ds').sum().reset_index()
daily_sales.head()

from prophet import Prophet
model = Prophet()
model.fit(daily_sales)

future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)
forecast.head()

import matplotlib.pyplot as plt
fig = model.plot(forecast)
plt.title("Sales Forecast using Prophet")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

fig2 = model.plot_components(forecast)
plt.show()

#monthly averages
import pandas as pd

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['YearMonth'] = df['Order Date'].dt.to_period('M')  # e.g., 2025-01

monthly_avg = df.groupby('YearMonth')['Sales'].mean().reset_index()
monthly_avg.rename(columns={'Sales': 'Monthly_Avg_Sales'}, inplace=True)

print(monthly_avg.head())

#holiday spikes
holidays = ['2024-01-01', '2024-12-25', '2024-11-28']
holidays = pd.to_datetime(holidays)

df['Is_Holiday'] = df['Order Date'].isin(holidays).astype(int)

holiday_sales = df[df['Is_Holiday'] == 1].groupby('Order Date')['Sales'].sum().reset_index()
print(holiday_sales)

forecast.to_csv('sales_forecast_for_powerbi.csv', index=False)

from google.colab import files
files.download('sales_forecast_for_powerbi.csv')